# Generated by Django 5.2.17 on 2026-10-06 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securityinfo', '0004_alter_nsesymbolinstrumentmap_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'announcement_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CorporateAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_id', models.BigIntegerField(unique=True)),
                ('announced_at', models.DateTimeField(db_index=True)),
                ('exchange_received_at', models.DateTimeField(blank=True, null=True)),
                ('attachment_text', models.TextField(blank=True)),
                ('attachment_url', models.URLField(blank=True, max_length=500)),
                ('attachment_file_size', models.CharField(blank=True, max_length=20)),
                ('has_xbrl', models.BooleanField(default=False)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='corporateannouncements.announcementcategory')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='securityinfo.instrument')),
            ],
            options={
                'db_table': 'corporate_announcements',
                'ordering': ['-announced_at'],
                'indexes': [models.Index(fields=['announced_at'], name='idx_announcement_date'), models.Index(fields=['instrument'], name='idx_announcement_instrument'), models.Index(fields=['category'], name='idx_announcement_category'), models.Index(fields=['instrument', 'announced_at'], name='idx_annc_instr_date')],
                'constraints': [models.UniqueConstraint(fields=('seq_id',), name='uniq_announcement_seq_id')],
            },
        ),
    ]
