# Generated by Django 5.2.17 on 2026-09-25 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dailypricehistory', '0004_alter_bhavcopyfile_id_alter_nsecmpricehistory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=10)),
                ('ticker', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'indices',
                'constraints': [models.UniqueConstraint(fields=('source', 'ticker'), name='uniq_index_source_ticker')],
            },
        ),
        migrations.CreateModel(
            name='IndexPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('open', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='index_price_rows', to='dailypricehistory.bhavcopyfile')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='indexpricehistory.index')),
            ],
            options={
                'db_table': 'index_price_history',
                'indexes': [models.Index(fields=['trade_date'], name='idx_index_price_date'), models.Index(fields=['index'], name='idx_index_price_index')],
                'constraints': [models.UniqueConstraint(fields=('index', 'trade_date'), name='uniq_price_index_date')],
            },
        ),
    ]
