# Generated by Django 6.1 on 2026-08-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("securityinfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BhavcopyFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255, unique=True)),
                ("source", models.CharField(max_length=10)),
                ("segment", models.CharField(default="CM", max_length=10)),
                (
                    "format",
                    models.CharField(
                        choices=[("legacy", "legacy"), ("udiff", "udiff")],
                        max_length=10,
                    ),
                ),
                ("trade_date", models.DateField()),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bhavcopy_files",
                "ordering": ["-trade_date"],
            },
        ),
        migrations.CreateModel(
            name="CmPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.DateField()),
                (
                    "open",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "prev_close",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "turnover",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=22, null=True
                    ),
                ),
                ("num_trades", models.IntegerField(blank=True, null=True)),
                (
                    "settlement_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_rows",
                        to="dailypricehistory.bhavcopyfile",
                    ),
                ),
                (
                    "instrument_ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="securityinfo.instrumentticker",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_history",
                        to="securityinfo.series",
                    ),
                ),
            ],
            options={
                "db_table": "cm_price_history",
                "indexes": [
                    models.Index(fields=["trade_date"], name="idx_cm_price_date"),
                    models.Index(
                        fields=["instrument_ticker"], name="idx_cm_price_ticker"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instrument_ticker", "trade_date", "series"),
                        name="uniq_price_ticker_date_series",
                    )
                ],
            },
        ),
    ]
