# Generated by Django 6.1 on 2026-08-31 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailypricehistory', '0001_initial'),
        ('securityinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CmPriceHistory',
            new_name='NSECmPriceHistory',
        ),
        migrations.AddField(
            model_name='nsecmpricehistory',
            name='instrument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='securityinfo.instrument'),
            preserve_default=False,
        ),
        migrations.RemoveIndex(
            model_name='nsecmpricehistory',
            name='idx_cm_price_ticker',
        ),
        migrations.RemoveConstraint(
            model_name='nsecmpricehistory',
            name='uniq_price_ticker_date_series',
        ),
        migrations.RemoveField(
            model_name='nsecmpricehistory',
            name='instrument_ticker',
        ),
        migrations.AddIndex(
            model_name='nsecmpricehistory',
            index=models.Index(fields=['instrument'], name='idx_cm_instrument'),
        ),
        migrations.AddConstraint(
            model_name='nsecmpricehistory',
            constraint=models.UniqueConstraint(fields=('instrument', 'trade_date', 'series'), name='uniq_price_instrument_date_series'),
        ),
    ]