# Generated by Django 6.1 on 2026-08-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailypricehistory', '0002_nsecmpricehistory_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nsecmpricehistory',
            table='nse_cm_price_history',
        ),
    ]
