# Generated by Django 5.2.17 on 2026-09-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypricehistory', '0003_alter_nsecmpricehistory_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhavcopyfile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='nsecmpricehistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
