# Generated by Django 4.2.30 on 2026-10-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFundAmc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'mutual_fund_amcs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'mutual_fund_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_code', models.BigIntegerField(unique=True)),
                ('scheme_name', models.CharField(max_length=255)),
                ('plan', models.CharField(blank=True, max_length=50)),
                ('option', models.CharField(blank=True, max_length=50)),
                ('isin_growth', models.CharField(blank=True, max_length=12, null=True)),
                ('isin_reinvest', models.CharField(blank=True, max_length=12, null=True)),
                ('scheme_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='mfnavhistory.mutualfundamc')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schemes', to='mfnavhistory.mutualfundcategory')),
            ],
            options={
                'db_table': 'mutual_fund_schemes',
                'ordering': ['scheme_code'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundNavHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_date', models.DateField()),
                ('nav', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_history', to='mfnavhistory.mutualfundscheme')),
            ],
            options={
                'db_table': 'mutual_fund_nav_history',
                'ordering': ['-nav_date'],
            },
        ),
        migrations.AddIndex(
            model_name='mutualfundscheme',
            index=models.Index(fields=['amc'], name='idx_mf_scheme_amc'),
        ),
        migrations.AddIndex(
            model_name='mutualfundscheme',
            index=models.Index(fields=['category'], name='idx_mf_scheme_category'),
        ),
        migrations.AddIndex(
            model_name='mutualfundscheme',
            index=models.Index(fields=['isin_growth'], name='idx_mf_scheme_isin_growth'),
        ),
        migrations.AddIndex(
            model_name='mutualfundscheme',
            index=models.Index(fields=['isin_reinvest'], name='idx_mf_scheme_isin_reinvest'),
        ),
        migrations.AddConstraint(
            model_name='mutualfundscheme',
            constraint=models.UniqueConstraint(fields=('scheme_code',), name='uniq_mf_scheme_code'),
        ),
        migrations.AddIndex(
            model_name='mutualfundnavhistory',
            index=models.Index(fields=['nav_date'], name='idx_nav_date'),
        ),
        migrations.AddIndex(
            model_name='mutualfundnavhistory',
            index=models.Index(fields=['scheme'], name='idx_nav_scheme'),
        ),
        migrations.AddConstraint(
            model_name='mutualfundnavhistory',
            constraint=models.UniqueConstraint(fields=('scheme', 'nav_date'), name='uniq_nav_scheme_date'),
        ),
    ]
