# Generated by Django 5.2.17 on 2026-09-24 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dailypricehistory', '0003_alter_nsecmpricehistory_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FnoContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underlying_symbol', models.CharField(max_length=50)),
                ('instrument_type', models.CharField(max_length=10)),
                ('expiry_date', models.DateField()),
                ('strike_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('option_type', models.CharField(blank=True, max_length=2, null=True)),
                ('fin_instrm_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fno_contracts',
                'indexes': [models.Index(fields=['expiry_date'], name='idx_fno_expiry')],
                'constraints': [models.UniqueConstraint(fields=('underlying_symbol', 'instrument_type', 'expiry_date', 'strike_price', 'option_type'), name='uniq_fno_contract')],
            },
        ),
        migrations.CreateModel(
            name='FnoPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('open', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('settlement_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('num_trades', models.IntegerField(blank=True, null=True)),
                ('open_interest', models.BigIntegerField(blank=True, null=True)),
                ('change_in_oi', models.BigIntegerField(blank=True, null=True)),
                ('underlying_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='fnopricehistory.fnocontract')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fno_price_rows', to='dailypricehistory.bhavcopyfile')),
            ],
            options={
                'db_table': 'fno_price_history',
                'indexes': [models.Index(fields=['trade_date'], name='idx_fno_price_date')],
                'constraints': [models.UniqueConstraint(fields=('contract', 'trade_date'), name='uniq_fno_price_contract_date')],
            },
        ),
    ]
