# Generated by Django 6.1 on 2026-08-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isin",
                    models.CharField(blank=True, max_length=12, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("instrument_type", models.CharField(default="STK", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "instruments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2, unique=True)),
                ("description", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "series",
                "db_table": "series",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="InstrumentTicker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=10)),
                ("ticker", models.CharField(max_length=50)),
                ("fin_instrm_id", models.IntegerField(blank=True, null=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickers",
                        to="securityinfo.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "instrument_tickers",
                "ordering": ["ticker", "source"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instrument", "source"), name="uniq_instrument_source"
                    ),
                    models.UniqueConstraint(
                        fields=("source", "ticker"), name="uniq_source_ticker"
                    ),
                ],
            },
        ),
    ]
