# Generated by Django 6.1 on 2026-08-31 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailypricehistory', '0002_nsecmpricehistory_and_more'),
        ('securityinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSESymbolInstrumentMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NSESymbols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nse_symbols',
            },
        ),
        migrations.RemoveConstraint(
            model_name='instrumentticker',
            name='uniq_instrument_source',
        ),
        migrations.RemoveConstraint(
            model_name='instrumentticker',
            name='uniq_source_ticker',
        ),
        migrations.AddField(
            model_name='nsesymbolinstrumentmap',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='securityinfo.instrument'),
        ),
        migrations.AddConstraint(
            model_name='nsesymbols',
            constraint=models.UniqueConstraint(fields=('symbol',), name='unique_symbol'),
        ),
        migrations.AddField(
            model_name='nsesymbolinstrumentmap',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='securityinfo.nsesymbols'),
        ),
        migrations.RemoveField(
            model_name='instrumentticker',
            name='instrument',
        ),
        migrations.AddConstraint(
            model_name='nsesymbolinstrumentmap',
            constraint=models.UniqueConstraint(fields=('symbol', 'instrument'), name='unique_symbol_instrument'),
        ),
        migrations.DeleteModel(
            name='InstrumentTicker',
        ),
    ]
