# Generated by Django 6.1 on 2026-08-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securityinfo', '0002_nsesymbolinstrumentmap_nsesymbols_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='isin',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
