# Generated by Django 6.1 on 2026-08-31 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securityinfo', '0003_alter_instrument_isin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nsesymbolinstrumentmap',
            table='nse_symbols_instrument_map',
        ),
    ]
